### ISSUE TITLE
Remove the "Register" button from Sign In screen

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#1]
## Description
The "Register" button is redundant in the Sign In screen and should be removed.
Edit: Also make the screen consistent with the `Register` screen (#8).

## Relevant file
[LoginPage.dart](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/LoginPage.dart)

## Screenshot
<img src="https://user-images.githubusercontent.com/74055102/141084864-8ddb66c4-1cf1-4e08-a1fd-9e93b9291fbe.png" height=500/>

**Comment by ehteshaxm** [comment]
Can I work on this?

**Comment by Saransh-cpp** [comment]
Sure, go ahead!

**Comment by Saransh-cpp** [comment]
@TESLA2402, this issue is currently taken. You can look out for other issues in this repository :)

**Comment by Saransh-cpp** [comment]
@ehteshaxm, any updates on this?

**Comment by Saransh-cpp** [comment]
The issue is open for now (due to inactivity).

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!
