### ISSUE TITLE
Add Google Sign In

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#10]
## Description
I think the Google Sign In has been implemented but has not been added to the frontend. Add it to the Register and Log In screen with all the necessary data. Adding this as hard as this will require passing the data in between files or initializing dummy data.

## Relevant files
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Utility/auth.dart
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/model/user.dart
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/Register.dart
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/LoginPage.dart

**Comment by mortal-ghost** [comment]
Can I work on this?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by mortal-ghost** [comment]
Can you please confirm if google sign in is enabled in firebase?

**Comment by Saransh-cpp** [comment]
![image](https://user-images.githubusercontent.com/74055102/144715153-5ee225e1-0d22-41ed-bccd-3d8661cf4f85.png)

Yes, do you want me to add you as a viewer in Firebase? If so, please drop your mail below.

**Comment by mortal-ghost** [comment]
anmoldeepsingh148@gmail.com

**Comment by Saransh-cpp** [comment]
![image](https://user-images.githubusercontent.com/74055102/144738885-9fdec71c-f22c-4d1c-ad2d-b26bd2554127.png)

Done!

**Comment by mortal-ghost** [comment]
I have written the code but the googleSignIn() function in auth.dart keeps giving me the same error. Error =>
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)
The error occurs on the second line of this function. I have searched about the error and keeps getting the same answer that there is some problem with firebase authentication. Here is a link to a stackoverflow answer I referred to -> https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google
I have checked the firebase. The chapter-3 app does have a sha1 key but the chapter3-admin does not. Is it possible that might be causing the error?

**Comment by mortal-ghost** [comment]
While working on the issue, I found another issue. On the home screen, the SingleChildScrollView widget is giving out an error. Can I raise this issue?

**Comment by Saransh-cpp** [comment]
Pointed out in #39

**Comment by Saransh-cpp** [comment]
I'll have a look at the error today

**Comment by mortal-ghost** [comment]
Thank you. I found another issue in the app. When you login with invalid credentials, the app logs in anyway with errors. Please take a look at this one too.

**Comment by Saransh-cpp** [comment]
Can you create a new issue with some screenshots or more details?

**Comment by mortal-ghost** [comment]
Yes I will

**Comment by Saransh-cpp** [comment]
> I have written the code but the googleSignIn() function in auth.dart keeps giving me the same error. Error =>
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null, null)

@mortal-ghost, can you create a PR so I can have a look?

**Comment by mortal-ghost** [comment]
I have created a PR. Can I start working on other issues ?
