### ISSUE TITLE
Error while running the project for android.

### ISSUE THREAD

**Issue by letsintegreat** [Saransh-cpp/BookRentApp-Chapter3#110]
The app is not getting installed because of some error:

![](https://i.imgur.com/IJZCZ8i.png)

To reproduce the error, try to run the app on the latest version of android. (API 31)

**Comment by Saransh-cpp** [comment]
Might change the difficulty based on the PR

**Comment by Saransh-cpp** [comment]
@all-contributors please add @letsintegreat for bug, platform
