### ISSUE TITLE
deprecated `firebase_admob` package 

### ISSUE THREAD

**Issue by Pranav108** [Saransh-cpp/BookRentApp-Chapter3#111]
# Description
In this app we have implemented `firebase_admob` package for showing mobile ads on myCart screen, which is deprecated now, instead we should use `google_mobile_ads` package. 

# Relevant files
`lib/Screens/YourOrders.dart`

# Screenshot
![image](https://user-images.githubusercontent.com/56934594/146670008-1adb6889-eb0d-42f4-8858-a4ca5d252480.png)

# References
[reference](https://pub.dev/documentation/firebase_admob/latest/#:~:text=The%20firebase_admob%20plugin%20will%20be,Mobile%20Ads%20SDK%20for%20Flutter.&text=It%20also%20supports%20displaying%20banner,overlayed%20over%20all%20app%20content.)

**Comment by rajoriaakash** [comment]
Hi, I would like to work on this...

**Comment by Saransh-cpp** [comment]
Go ahead!
