### ISSUE TITLE
Renderflex overflow in cart screen

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#115]
# Description
Make the screen dynamic.

# Relevant files
- `YourOrders.dart`

# Screenshot
<img src="https://user-images.githubusercontent.com/74055102/147943913-e5abf3eb-7cd4-4cab-b197-f05b54259423.png" height=500/>

**Comment by noman2002** [comment]
I am willing to work on this issue please assign it to me.

**Comment by noman2002** [comment]
I am unable to recreate this issue. On my emulator it is working fine in both pixel 4a and pixel 4XL. Can you please help me out.

**Comment by Saransh-cpp** [comment]
Try pixel 2

**Comment by noman2002** [comment]
> Try pixel 2
ok

**Comment by noman2002** [comment]
> Try pixel 2

ok
