### ISSUE TITLE
Drop in your emails if you are working on anything related to backend

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#12]
I will add you all to the Firebase console as a viewer, so that you can see all the stored dummy data.

**Comment by mortal-ghost** [comment]
I noticed in the firebase, sign in anonymous option is on but it is not implemented. Does it need to be implemented?

**Comment by Saransh-cpp** [comment]
Nope, that is for the admins (private app🤫).
