### ISSUE TITLE
Implement the "Report issue" option

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#120]
# Description
There are a lot of tools available on the internet that integrates with our app and let a user report bug/glitch with extra information. Look out for such SDKs and integrate with the app.

# Screenshot
<img src="https://user-images.githubusercontent.com/74055102/147945402-8a31b269-834a-41ff-aaa3-70f33892e150.png" height=500/>

# References
- https://github.com/smaranjitghose/DocLense

**Comment by letsintegreat** [comment]
I'd like to work on this issue.
