### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#13]
## Description
Add a splash screen in the application with the app's logo.

## Resources
https://whiteviolin.medium.com/creating-splash-screens-in-flutter-apps-8a284d86aa1b

## Logo
![IMG-20201209-WA0078](https://user-images.githubusercontent.com/74055102/141179679-5ce3381d-1f01-4888-9b4e-0ee6bb305c84.jpg)

**Comment by shrinishant** [comment]
@Saransh-cpp sir, I would like to integrate the splash screen for the app? Could you please assign this to me?

**Comment by shrinishant** [comment]
No Saransh, I'm a SWOC Participant. Can I still work on this and be assigned ?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by Pranav108** [comment]
@Saransh-cpp  I'm a CodePeak participant, if this thread is not active so can I take it?

**Comment by Saransh-cpp** [comment]
@shrinishant, any updates on this?

**Comment by Saransh-cpp** [comment]
The issue is open for now (due to inactivity).

**Comment by Pranav108** [comment]
Can I take it?

**Comment by Saransh-cpp** [comment]
I will assign you once #49 is merged

**Comment by Pranav108** [comment]
Can I start working on it?

**Comment by Pranav108** [comment]
Splash loading screen is already in the app and is working well so I have to only add `True Splash Screen` , means the changes in res folder, right?

**Comment by Saransh-cpp** [comment]
Can you update the existing splash screen to also contain the logo? Other than that, yes, only the true splash screen is needed.

**Comment by Saransh-cpp** [comment]
Yes, anything that you like. I am comfortable with both options!
