### ISSUE TITLE
Add a workflow to label issues

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#15]
## Description

Create a workflow to label issues with the tag `CodePeak`, and `SWoC`.
## References
- https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues

**Comment by Vaibhav-Chopra-GT** [comment]
can I work on this issue?

**Comment by Saransh-cpp** [comment]
Sure! Go ahead!
