### ISSUE TITLE
Error while building the project.

### ISSUE THREAD

**Issue by letsintegreat** [Saransh-cpp/BookRentApp-Chapter3#16]
We cannot build and run the project for android using the latest SDK as it uses old versions for some dependencies, e.g. win32.

Screenshot of the error message:
![](https://i.imgur.com/ABDtsmk.png)

**Comment by letsintegreat** [comment]
I'd like to work on this issue and update versions of all the dependencies to their latest values.

**Comment by Saransh-cpp** [comment]
Weird, I haven't updated Flutter in a while. Can you paste the stack trace here instead of the screenshot? If you know where the issue is, then go ahead!

**Comment by letsintegreat** [comment]
@Saransh-cpp 

> Weird, I haven't updated Flutter in a while. Can you paste the stack trace here instead of the screenshot?

Here is the complete error message with stack trace: https://pastebin.com/hPviJSUn
Stack trace at line number 241.

**Gradle 6.3**
**Flutter 2.6.0-12.0.pre.871**
**Dart 2.16.0**

> If you know where the issue is, then go ahead!

I know how to get it fixed, and I will make a PR shortly after CodePeak coding period starts.
