### ISSUE TITLE
Incorrect branch name in README.md

### ISSUE THREAD

**Issue by letsintegreat** [Saransh-cpp/BookRentApp-Chapter3#18]
> 2. Pull the latest code in.
>     ```
>    # make sure you are on the main branch
>     git pull upstream main
>      ```

The branch name in [upstream](https://github.com/Saransh-cpp/BookRentApp-Chapter3) is master, not main. It needs to be fixed.

**Comment by letsintegreat** [comment]
I'd like to work on this issue.

**Comment by Saransh-cpp** [comment]
Go ahead!
