### ISSUE TITLE
Add all the screens to `README`

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#2]
## Description
Add a compiled image of all the screens in the README file.

## References
- https://github.com/smaranjitghose/DocLense#app-screens
- https://app-mockup.com/

**Comment by hurshh** [comment]
@Saransh-cpp can I take this issue???

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by Saransh-cpp** [comment]
@hurshh, any updates on this?

**Comment by hurshh** [comment]
there is noting in homescreen so should i keep homescreen??

**Comment by Saransh-cpp** [comment]
Keep all the screens as they are, the "home screen content not visible" bug was fixed recently, make sure you are on the latest commit.
