### ISSUE TITLE
Renderflex overflow in home screen

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#20]
## Screenshot
<img src="https://user-images.githubusercontent.com/74055102/144561225-349d9a49-7ed0-47e2-add6-2dc6d4c08aac.png" height=500/>

**Comment by TESLA2402** [comment]
Can I solve this issue?
Name : Lakshay

**Comment by Saransh-cpp** [comment]
Sure, go ahead @TESLA2402!
