### ISSUE TITLE
Revamp the drawer

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#21]
## Description
The drawer right now looks ugly, create a new design and implement it in the app. You might also need to create a new widget for the tiles and refactor some code (hence putting this issue as a hard one).

## Screenshot
<img src="https://user-images.githubusercontent.com/74055102/144561465-9e340880-8331-4d8f-ae25-fe773929c91d.png" height=500/>

**Comment by Keshab0100** [comment]
I would love to try to solve this issue, may I?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by Keshab0100** [comment]
great

**Comment by Keshab0100** [comment]
Where can I connect with you for any queries?

**Comment by Saransh-cpp** [comment]
Are you a part of any program? (CodePeak or SWoC)?

**Comment by Keshab0100** [comment]
Ya, swoc

**Comment by Saransh-cpp** [comment]
Is the Chapter3 discord channel accessible to you?

**Comment by Keshab0100** [comment]
No

**Comment by Saransh-cpp** [comment]
There is somewhere an option to get a specific project's role (as a participant). You can ask other participants in the general chat, I can't see those roles, probably because I am not a participant.

**Comment by Keshab0100** [comment]
Ya, there is a bot that assigns role by reacting to a message, but it seems it is not working, I haven't got the role

**Comment by Saransh-cpp** [comment]
![image](https://user-images.githubusercontent.com/74055102/144749069-82beb839-a432-44c6-9bed-06d194f86130.png)

@Keshab0100, I think the bot has been fixed now.

**Comment by Pranav108** [comment]
If this issue is inactive then can I give it a try?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by Pranav108** [comment]
@Saransh-cpp can you please elaborate the task a bit.

**Comment by Keshab0100** [comment]
I was busy with my internals😅

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp can you please elaborate the task a bit.

Sorry for the delay. I think a white background would look nice, with no weird orange and pink color (XD)? Plus I think it would look good if you could only fix the My Orders tile.

**Comment by letsintegreat** [comment]
If this issue is still unresolved and no one's working on it, I'd like to work.

**Comment by startlingmind** [comment]
I would like to work on this

**Comment by Saransh-cpp** [comment]
> I would like to work on this

Hi @startlingmind, I'll assign this to @letsintegreat for now. You can have a look at other open issues!
