### ISSUE TITLE
Create the `About` Screen

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#27]
## Description
Create the `About` screen from scratch -
- Come up with a short description of the app.
- Make the screen visually appealing (you can use [undraw's](https://undraw.co/) illustrations)
- Make an `Author` section and add me (GitHub profile).
- Make a `Contributors` section, and show all the contributors in a grid view using GitHub's API.

## Relevant file
- [AboutUs.dart](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/AboutUs.dart)

## Reference
<img src="https://user-images.githubusercontent.com/74055102/144701454-c6cc66b0-5527-4673-89d3-73617a700398.png" height=500/>

**Comment by Pranav108** [comment]
Sounds new to me but would love to give it a try, can I work on it?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by Pranav108** [comment]
I never worked with github api before, can you please guide me how can I get those api of contributors in any repository  ,I searched but didn't got anything helpful.

**Comment by Saransh-cpp** [comment]
Here is the code for the above reference - [file](https://github.com/smaranjitghose/DocLense/blob/main/lib/settings/contact_developers.dart)

They've used the API in here, let me know if you face any difficulties.

**Comment by Saransh-cpp** [comment]
https://api.github.com/repos/Saransh-cpp/BookRentApp-Chapter3/contributors

For this repository

**Comment by Pranav108** [comment]
Thanks for the resources ,they helped me a lot.
This is what I have created yet ,something else I should add in this section?
![about_section](https://user-images.githubusercontent.com/56934594/144792280-499e11ca-7d7b-437a-8b9f-0e5d264b558a.gif)

**Comment by Saransh-cpp** [comment]
This looks great! Can you create a PR? Might have some minor iterations.
