### ISSUE TITLE
Remove unnecessary imports

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#3]
## Description
There are a lot of unnecessary imports in almost all of the files, they should be removed.

**Comment by justdoit254** [comment]
@Saransh-cpp I am a beginner can I work on this issue.

**Comment by Saransh-cpp** [comment]
Yes, go ahead!

**Comment by Saransh-cpp** [comment]
@justdoit254, any updates on this?

**Comment by justdoit254** [comment]
Yes, @Saransh-cpp as I am a beginner so I was just learning how to use git I will update you today by evening.
Sorry for the delay.

**Comment by justdoit254** [comment]
Can you please help me out as I am not understanding which file should I fork first.

**Comment by Saransh-cpp** [comment]
You should fork the complete repository (you cannot fork a file) using the fork button (extreme right).

![image](https://user-images.githubusercontent.com/74055102/144762011-d6e30c48-ce72-4a19-ad9a-5e4154072c3f.png)

**Comment by Saransh-cpp** [comment]
> Yes, @Saransh-cpp as I am a beginner so I was just learning how to use git I will update you today by evening. Sorry for the delay.

No issues! Take your time.

**Comment by justdoit254** [comment]
Is is necessary having flutter in my laptop to work on the issue?

**Comment by justdoit254** [comment]
> > Yes, @Saransh-cpp as I am a beginner so I was just learning how to use git I will update you today by evening. Sorry for the delay.
> 
> No issues! Take your time.

Thank you

**Comment by Saransh-cpp** [comment]
> Is is necessary having flutter in my laptop to work on the issue as mentioned in the README?

Yes, you'll have to check if the app is working fine after removing the imports.

**Comment by justdoit254** [comment]
I have cloned the repository in my VScode can you please guide me for the next step.

**Comment by justdoit254** [comment]
I am not able to identify which file should I open and start working on the issue.

**Comment by Saransh-cpp** [comment]
All the `dart` files are available in the `lib` directory and its subdirectories. You can pick any one of them and start working!

**Comment by justdoit254** [comment]
@Saransh-cpp  can I do the required changes in VScode itself or do I need to get android studio.

**Comment by justdoit254** [comment]
Do I need to install android studio or I can make the required changes in VScode only.

**Comment by Saransh-cpp** [comment]
You can do it any IDE, just make sure that the app works.

**Comment by Saransh-cpp** [comment]
@justdoit254, any updates?

**Comment by atharv-bhadange** [comment]
Hey! Can I do this?

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!
