### ISSUE TITLE
Revamp `AllBooks` screen

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#37]
## Description

Right now the screen looks very dull. I'd like to keep the overall structure of the screen and the cards, but the rest of everything can be updated.

<img src="https://user-images.githubusercontent.com/74055102/144751819-e750a4d2-61b5-4102-92ab-7484db35b1f1.png" height=500/>

**Comment by hurshh** [comment]
I think changing the scaffold colour to pink that matches the bottom navbar and increasing the genre font will make it beautiful
![screenshot1 (1)](https://user-images.githubusercontent.com/75796695/144890773-a8d5546c-2190-4f5f-b93e-855d2c479f90.png)

**Comment by Saransh-cpp** [comment]
@hurshh looks good, might need some iterations, but I can assign you 1 issue at a time. Are you done with #2?

**Comment by hurshh** [comment]
> @hurshh looks good, might need some iterations, but I can assign you 1 issue at a time. Are you done with #2?

ill try my best to complete #2  by today

**Comment by Vaibhav-Chopra-GT** [comment]
can I work on this issue?

**Comment by Saransh-cpp** [comment]
Yes, as you cannot work on #50 right now, go ahead!
