### ISSUE TITLE
Lint all the files

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#4]
## Description
Right now the file names and the code is not linted properly (or does not follow the convention naming etc.). Lint all the files.

## Multiple contributors
This issue can have multiple PRs but each PR should lint at least 3 files.

**Comment by Starkl7** [comment]
I would like to work on this as part of SWOC'21. Could you assign this issue to me?

**Comment by Saransh-cpp** [comment]
@Starkl7, any updates on this?

**Comment by Starkl7** [comment]
@Saransh-cpp I have finished linting all the files in lib, except those in Screens, will be submitting a PR by tonight for review.

**Comment by Starkl7** [comment]
@Saransh-cpp I have created the pull request. Please review it.
Apologies for the delay, faced a few issues with version control.

**Comment by Starkl7** [comment]
Should I proceed with the rest of the project?

**Comment by Saransh-cpp** [comment]
Re-opening this as #114 adds some more lint checks which would require the files to be formatted.
