### ISSUE TITLE
Create an issue template

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#41]
## Description
Create an issue template. The template would look something like this -

## References

**Comment by Saransh-cpp** [comment]
@pushkar2112, this one!

**Comment by pushkar2112** [comment]
can I take this one?

**Comment by Saransh-cpp** [comment]
Go ahead!

**Comment by pushkar2112** [comment]
What would be the title of the template?

**Comment by Saransh-cpp** [comment]
Create a PR, I'll suggest changes there.
