### ISSUE TITLE
Create a pull request template

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#42]
Should look something like -

**Program** -
**Fixes**
## Checklist
- [ ] The app builds properly
- [ ] Code is commented in difficult to understand areas
- [ ] Code is formatted well

**Comment by pushkar2112** [comment]
Hey, 
I would like to work on this issue.

**Comment by Saransh-cpp** [comment]
@pushkar2112 this issue has been solved, my bad. You can take a look at #41, a similar issue!
