### ISSUE TITLE
Logging in with Invalid Credentials

### ISSUE THREAD

**Issue by mortal-ghost** [Saransh-cpp/BookRentApp-Chapter3#45]
The app lets us login with invalid email and password. We can put any non-empty email like '123' and any password with more than 6 characters and sign in to the app. But the home screen and cart screen will display an error as shown ->
<img src="https://user-images.githubusercontent.com/83603918/144825381-592487ca-47db-481f-8a05-b0cb72b1ca2b.png" height=500/>
<img src="https://user-images.githubusercontent.com/83603918/144825389-f570d10f-b3b7-4cb4-891b-e0e3eb14c33b.png" height=500/>

**Comment by Saransh-cpp** [comment]
@all-contributors please add @mortal-ghost for bug

**Comment by mortal-ghost** [comment]
Can I work on this now?

**Comment by Saransh-cpp** [comment]
Yes! I am not getting the time to go through #56 in detail. You can take this up.

**Comment by mortal-ghost** [comment]
This one is fixed.
![WhatsApp Image 2021-12-08 at 2 53 03 PM](https://user-images.githubusercontent.com/83603918/145182972-2d1d2837-2ca7-4e7f-853f-1fa3090414eb.jpeg)
But the google sign in still does not work.

**Comment by mortal-ghost** [comment]
I also found a overflow on a widget on the home screen. I found the fix too. Do I need to create another issue?

**Comment by Saransh-cpp** [comment]
> This one is fixed.

Can you create a PR?

**Comment by Saransh-cpp** [comment]
> I also found a overflow on a widget on the home screen. I found the fix too. Do I need to create another issue?

Yes, create a new issue.

**Comment by mortal-ghost** [comment]
This issue is fixed after the addition of google sign in button which does not work. Should I remove it or let it be for this PR?
