### ISSUE TITLE
Implement a lint checker CI pipeline

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#5]
## Description
Add a workflow that checks the linting of the codebase on every `pull_request`, `push` and `schedule`.

## References
- https://github.com/smaranjitghose/DocLense/blob/main/.github/workflows/ci.yml

**Comment by Vaibhav-Chopra-GT** [comment]
Can i work on this issue?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!
