### ISSUE TITLE
need improvement in deprecated syntax

### ISSUE THREAD

**Issue by Pranav108** [Saransh-cpp/BookRentApp-Chapter3#50]
Throughout the code we can see many deprecated widget (e.g. RaisedButton, showSnackBar etc .) which may cause unexpected behavior in future, so this syntax need to be replaced with their latest alternative.

**Comment by Saransh-cpp** [comment]
These deprecations will be easily visible through GitHub Actions once #5 is solved. Thanks for pointing this out!

**Comment by Vaibhav-Chopra-GT** [comment]
Can I work on this issue

**Comment by Saransh-cpp** [comment]
Yes, go ahead! Just wait for #60 to be merged.

**Comment by Saransh-cpp** [comment]
@Vaibhav-Chopra-GT, you can go ahead now!
