### ISSUE TITLE
Remove `<br>` from PR template

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#54]
## Description

The PR template has a lot of unnecessary line breaks (`<br>`). Remove all of them.

## Relevant file
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by pushkar2112** [comment]
I would like to solve this one too... can I go ahead with this too?

**Comment by Saransh-cpp** [comment]
@pushkar2112, one issue at a time :) which one would you like to work on?

**Comment by pushkar2112** [comment]
the issue template

**Comment by pushkar2112** [comment]
can i work on this one now?
