### ISSUE TITLE
Remove redundant files

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#6]
## Description
I think [Wrapper.dart](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Wrapper.dart) and [database.dart](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/database.dart) are redundant. Remove them and make sure that it doesn't break anything.

**Comment by atharv-bhadange** [comment]
I am a beginner, can I work on this?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!
