### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#61]
# Description
2 badges should be added below the Chapter 3 logo, and the existing badge should also be moved there.

Two badges -
- [![Flutter/Dart Lint Check](https://github.com/Saransh-cpp/BookRentApp-Chapter3/actions/workflows/Test.push.yml/badge.svg)](https://github.com/Saransh-cpp/BookRentApp-Chapter3/actions/workflows/Test.push.yml)
- [![Label issues](https://github.com/Saransh-cpp/BookRentApp-Chapter3/actions/workflows/App.yml/badge.svg)](https://github.com/Saransh-cpp/BookRentApp-Chapter3/actions/workflows/App.yml)

# Relevant files
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/README.md

# Screenshot
Please attach screenshots for the same, if applicable

# References
- https://github.com/pybamm-team/BattBot#readme

**Comment by pushkar2112** [comment]
Can I work on this issue?

**Comment by Saransh-cpp** [comment]
Yes, go ahead!
