### ISSUE TITLE
Implement "All contributors" section

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#7]
## Description
It would be nice to have an all contributors section in the `README` file.

## References
Preference 1 - https://github.com/pybamm-team/PyBaMM#-contributors
Preference 2 - https://github.com/smaranjitghose/DocLense#our-valuable-contributors-

Let me know if I have to enable something in order to implement this!

**Comment by Pranav108** [comment]
Can I work on it?

**Comment by Saransh-cpp** [comment]
Sure, go ahead! Try to implement the `Preference 1` section.

**Comment by Pranav108** [comment]
I can see 5 account who have contributed  to master, excluding merge commits and bot accounts.
So I have to add these 5 users only, right?

**Comment by Saransh-cpp** [comment]
Let me try this

**Comment by Saransh-cpp** [comment]
@all-contributors please add @Saransh-cpp for code

**Comment by Saransh-cpp** [comment]
Oh this was easy XD I'll ask the CodePeak admins about how to mark you on this

**Comment by Saransh-cpp** [comment]
I've marked you accordingly! Thanks for the quick fix!

**Comment by Saransh-cpp** [comment]
@all-contributors please add @Pranav108 for ideas
