### ISSUE TITLE
Adding functionality for contactUs section

### ISSUE THREAD

**Issue by Pranav108** [Saransh-cpp/BookRentApp-Chapter3#71]
# Description
We have a `Contact us` section but it doesn't do anything yet. Adding some non-void functionality to this section will enhance the app. 

# Relevant files
lib/Screens/Contact.dart

# Screenshot
NotApplicable

# References
NotApplicable

**Comment by Saransh-cpp** [comment]
Do you want to take this up?

**Comment by Pranav108** [comment]
Yeah , I would like to.
Can you give basic overview about it , what functionality you expect here?

**Comment by Saransh-cpp** [comment]
Something like the about us screen

<- Contact
Do you have an issue, or do you want a new functionality, or are you looking for some random answers? Contact us here -
GitHub repository - link
GitHub issues - link
GitHub discussions - link
Author's LinkedIn - link
Author's GitHub - link
