### ISSUE TITLE
Revamp the Shopping Cart screen

### ISSUE THREAD

**Issue by Vaibhav-Chopra-GT** [Saransh-cpp/BookRentApp-Chapter3#74]
# Description
The shopping Cart screen looks very dull and the checkout button does not match the aesthetic of the app.
Also, the Your cart is empty pop-up looks plain

# Screenshot
<img src="https://user-images.githubusercontent.com/92637595/145412247-d92dd034-1476-494c-b91f-630b319647fa.png" height=500/>

<img src="https://user-images.githubusercontent.com/92637595/145412155-49c8365b-eda1-44ee-84e7-ccd716f2a5df.png" height=500/>

**Comment by Pranav108** [comment]
@Saransh-cpp Can I take it?

**Comment by Saransh-cpp** [comment]
Yes, some suggestions -

- Update the button
- Show something if the cart is empty
- Update the app bar
- Change the background color
- Check how the item cards are displayed
- Check how the alert message on ordering something is displayed

**Comment by startlingmind** [comment]
Can you assign me this?

**Comment by Pranav108** [comment]
> Can you assign me this?

@startlingmind A [PR](https://github.com/Saransh-cpp/BookRentApp-Chapter3/pull/83) is already for this issue.

**Comment by Pranav108** [comment]
> > Can you assign me this?
> 
> @startlingmind A [PR](https://github.com/Saransh-cpp/BookRentApp-Chapter3/pull/83) is already running for this issue.
