### ISSUE TITLE
Add "Program" section in the PR template.

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#75]
# Description
Add "Program" section in the PR template.

# Relevant files
- https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by akshatjain1004** [comment]
Hi I'd like to work on this!

**Comment by akshatjain1004** [comment]
Can you tell me what should it include? @Saransh-cpp

**Comment by Saransh-cpp** [comment]
Above everything add this -

**Program that you are a part of -**
- [ ] CodePeak
- [ ] Script Winter of Code
- [ ] None

**Comment by akshatjain1004** [comment]
Understood! Can you assign it to me? Ps. I'm a codepeak participant
