### ISSUE TITLE
Make the UI of `Register` screen uniform

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#8]
## Description
Right now the register screen looks really bad (well, the whole app looks really bad), for starters, we can try making the UI on a single screen a bit uniform.
- Add white background in all the fields
- Create a similar eye icon in confirm password field

## Relevant screens
[Register.dart](https://github.com/Saransh-cpp/BookRentApp-Chapter3/blob/master/lib/Screens/Register.dart)

## Screenshot
<img src="https://user-images.githubusercontent.com/74055102/141091932-d67f383b-635d-49df-aaf6-eaf28fe76250.png" height=500/>

**Note** - You might also would need to refactor the code by creating a new widget (hence I am keeping this a moderate level issue)

**Comment by raviyadav17** [comment]
Can I solve this issue?
Name : Ravi

**Comment by Saransh-cpp** [comment]
Sure, go ahead!

**Comment by raviyadav17** [comment]
![Register Screen](https://user-images.githubusercontent.com/86602971/144599108-d7f41395-4075-4627-967c-716ed26367eb.jpeg)
Is This UI ok

**Comment by raviyadav17** [comment]
**Is This UI okay**

![Register Screen](https://user-images.githubusercontent.com/86602971/144599241-7f60c1f0-6403-4961-a9bc-67b4746f283d.jpeg)

**Comment by raviyadav17** [comment]
**IS THIS UI OKAY**
<img src="https://user-images.githubusercontent.com/86602971/144599814-e42927b3-fba5-490a-8e49-dbf99a8605f8.jpeg" width=30% height=30%>

**Comment by Saransh-cpp** [comment]
Yes, looks good! Could you also decrease the width of the input fields? So that they don't take the complete width of a device.

**Comment by raviyadav17** [comment]
**Done **
<img src="https://user-images.githubusercontent.com/86602971/144602590-cedce171-c2b8-4cb2-b972-edaf0ccb568f.jpeg"
width=30% height=30%>

**Comment by Saransh-cpp** [comment]
Looks good! You can create a PR.
