### ISSUE TITLE
Overflow of widgets in landscape mode

### ISSUE THREAD

**Issue by mortal-ghost** [Saransh-cpp/BookRentApp-Chapter3#87]
# Description
The home screen and login screen has overflowing widgets in landscape mode. Other screens may be affected too.
Login screen only has overflow when typing the email and password.

# Relevant files
lib/Screens/Home.dart
lib/Screens/LoginPage.dart

# Screenshot
![Screenshot_1639317957](https://user-images.githubusercontent.com/83603918/145716108-381a3317-b6e0-4e8d-aa2d-7e66791edbc4.png)
![Screenshot_1639318001](https://user-images.githubusercontent.com/83603918/145716109-e14518b0-52b0-41da-8b8a-0cf974fc1eed.png)

**Comment by mortal-ghost** [comment]
Can I also work on this?

**Comment by mortal-ghost** [comment]
Other screens are also affected. 
![Screenshot_1639333954](https://user-images.githubusercontent.com/83603918/145725116-58534bac-fd09-4302-b79a-e012d6332fbd.png)
![Screenshot_1639333992](https://user-images.githubusercontent.com/83603918/145725118-ce48e44e-b586-45de-83e8-1e5eb28639cb.png)
![Screenshot_1639334161](https://user-images.githubusercontent.com/83603918/145725119-4cd0b320-600c-4c55-a3b8-7d01e8d3f9e5.png)

**Comment by Saransh-cpp** [comment]
@mortal-ghost, I am thinking of restricting the app to portrait mode. What do you think?

**Comment by mortal-ghost** [comment]
Yes, I think that would be better. The UI seems better for the portrait mode

**Comment by Saransh-cpp** [comment]
Yes, you can take this up!

**Comment by mortal-ghost** [comment]
I just pulled the upstream master and found another issue  :sweat_smile: .  Create another one?

![Screenshot_1639336563](https://user-images.githubusercontent.com/83603918/145726558-a5dc1998-69e8-4afb-912c-734c4ab136da.png)

**Comment by Saransh-cpp** [comment]
The app is behaving weirdly, I am guessing we messed something up in a PR. Yes, create a new issue (please add the steps to reproduce).
