### ISSUE TITLE
Error on register screen 

### ISSUE THREAD

**Issue by mortal-ghost** [Saransh-cpp/BookRentApp-Chapter3#89]
# Description
The register screen throws an error anytime it is opened.

# Relevant files
lib/Screens/Register.dart

# Screenshot
![Screenshot_1639336563](https://user-images.githubusercontent.com/83603918/145726990-f1eb49dd-c0d6-47ce-a57b-198f3bfa7a73.png)

**Comment by mortal-ghost** [comment]
I found the problem. Can I fix this one too?

**Comment by startlingmind** [comment]
Please assign me this

**Comment by msramesh2k1** [comment]
> I found the problem. Can I fix this one too?

Go ahead

**Comment by naveeramesh** [comment]
> The app is behaving weirdly on signing in and out. Signing out does not push to login screen and logging in with wrong credentials does not display a snackbar but stays as it is. Can you please confirm if these are new issues or issues with my device?

Yes I had checked there is an issue in signin and signout so leme create a new issue or @Saransh-cpp will you create it?

**Comment by Saransh-cpp** [comment]
@mortal-ghost can create one

**Comment by Saransh-cpp** [comment]
@all-contributors please add @naveeramesh for mentoring

**Comment by Saransh-cpp** [comment]
@all-contributors please add @naveeramesh for mentoring
