### ISSUE TITLE
Stylify the README file

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#9]
## Description
The README right now looks ugly. Things to do -
1. Centre align all the images.
2. There are some numbering issues, fix them.
3. Fix spelling mistakes.
4. Make sure all the links work.
5. Add some emojis in the headings.
6. Also the logo looks weird, crop the logo in such a way that it take all the width.
The file -
![IMG-20201209-WA0078](https://user-images.githubusercontent.com/74055102/141179679-5ce3381d-1f01-4888-9b4e-0ee6bb305c84.jpg)

## References
1. https://github.com/pybamm-team/PyBaMM#readme
2. https://github.com/smaranjitghose/DocLense#readme

**Comment by Youspeakcubic** [comment]
Howdy, Would love to work on this, could i be assigned?

**Comment by Saransh-cpp** [comment]
Sure! Go ahead!
