### ISSUE TITLE
Weird app behaviour

### ISSUE THREAD

**Issue by Saransh-cpp** [Saransh-cpp/BookRentApp-Chapter3#92]
# Description
The app is behaving very weirdly in different situations. One that I encountered -
1. Add a book to the cart (notice how the cart icon disappears)
2. Go to the cart screen (notice how it loads for a long time) and place an order/delete the items
3. Go back and open any books (It won't open)
4. The app is stuck in a weird place where nothing is working

The bug is somewhere between the commit 3a3c330a96ebfb5b6242b8cc3cb4a7eae570a623 and the latest commit for sure.

**Comment by mortal-ghost** [comment]
Is the login and logging out issue covered in this ?

**Comment by mortal-ghost** [comment]
Can I work on this?

**Comment by msramesh2k1** [comment]
> Is the login and logging out issue covered in this ?

No

**Comment by msramesh2k1** [comment]
> Can I work on this?

@Saransh-cpp

**Comment by msramesh2k1** [comment]
> Is the login and logging out issue covered in this ?

@Saransh-cpp told you to create seperate issue for this

**Comment by mortal-ghost** [comment]
Ok I will create another issue

**Comment by Saransh-cpp** [comment]
> Can I work on this?

You've already been assigned 1 issue. You take this up after that!

**Comment by mortal-ghost** [comment]
Now can I please work on this one?

**Comment by arnav1776** [comment]
@mortal-ghost Sure go ahead.

**Comment by mortal-ghost** [comment]
I fixed these issues. Should I wait for the last PR to close or just create a new one ?

**Comment by msramesh2k1** [comment]
You can create PR

**Comment by msramesh2k1** [comment]
> I fixed these issues. Should I wait for the last PR to close or just create a new one ?  

I will review the PR by tomorrow
