### ISSUE TITLE
Issues with signing in and signing out

### ISSUE THREAD

**Issue by mortal-ghost** [Saransh-cpp/BookRentApp-Chapter3#94]
# Description
On signing in with incorrect credentials. the app does not display a snackbar about the failed sign in.
On signing out, the login screen is not pushed to the screen, instead it just stays signed in until we restart the app.

# Relevant files
lib/Screens/LoginPage.dart
lib/Screens/Home.dart
Could be many others

**Comment by mortal-ghost** [comment]
Ok I finally fixed the issues but assigning this issue an easy label seems a bit harsh :slightly_frowning_face: . Was very hard to find with run log giving almost no warning.

**Comment by Saransh-cpp** [comment]
@mortal-ghost, I'll look into the difficulty once I review the PR!

**Comment by mortal-ghost** [comment]
> @mortal-ghost, I'll look into the difficulty once I review the PR!

Thanks
